openapi: "3.0.0"
info:
  title: "Datahog API"
  version: "1.0.0"
paths:
  /:
    get:
      summary: "Endpoint for checking if the API is available."
      responses:
        "200":
          description: "Indicates the API is running"
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
    post:
      summary: "Endpoint for requesting data collection."
      parameters:
        - description: "Name of provider to collect data from"
          in: query
          name: provider
          required: true
          schema:
            enum:
              - gas
              - internet
            type: string
        - description: "Publicly accessible endpoint to call back with collected data"
          in: query
          name: callbackUrl
          allowReserved: true
          required: true
          schema:
            format: uri
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
        "500":
          description: Invalid request
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
  /spec:
    get:
      summary: "Endpoint for requesting this API schema."
      responses:
        "200":
          description: "API schema returned"
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array